### PR TITLE
Getting up to speed

### PR DESCRIPTION
**Pull request by Cinderella-Man**
Hi,

As I was looking for something else on the web, I got amazed that you bring FP to PHP - great idea/job!
This pull request does some low hanging fruits. `init` method just to follow FP naming and misspelling fix: https://wiki.haskell.org/Currying

Init is taken from here: http://zvon.org/other/haskell/Outputprelude/init_f.html

Please look at the section 'Related:' - there's plenty of functions missing in this library like:
`drop`, `dropWhile`, `takeWhile`, `sortBy`, `reverse`

If you want some help I'm more than happy to add at least 5 functions.

PS. I understand that inspiration comes from Scala/underscore but bigger players in FP world are Haskell/Ramda - probably worth looking at those.

### CODE REVIEW

**Comment by lstrojny** [comment]
Thanks for the PR, can you remove the `init()` part from it for the time being so I can merge the doc changes independently?

**Comment by Cinderella-Man** [comment]
`init()` removed, now PR contains only docs change

**Comment by lstrojny** [comment]
Thank you!

**Comment by Cinderella-Man** [comment]
any feedback on `init()` and the others? I would be keen to help to expand the library

**Pull request merged**
