### PR TITLE
const_function() and id()

### PR DESCRIPTION
**Pull request by alexeyshockov**
I found useful having constant function in my projects (like Function.const() in Scala), and want to share it.

Some use cases:
* create a callable from a value in a place, where you need a callable,
* wrap another callable, when you need it as a value.

### CODE REVIEW

**Comment by lstrojny** [comment]
Thanks for sharing. Can you add some exemplary use cases to the documentation?

**Comment by alexeyshockov** [comment]
Of course. I created new chapter in documentation, because I think this functions aren't match any existing one.

**Comment by lstrojny** [comment]
If you could squash the commits we are good to go.

**Comment by alexeyshockov** [comment]
No problem, but I think all this commits are better separatly: documentation fixes are not connected with feature itself.

**Comment by alexeyshockov** [comment]
Squashed them.

**Comment by lstrojny** [comment]
Thanks again, merged

**Pull request merged**
