### PR TITLE
Add file comments

### LINKED ISSUE #199: Porper file comment instead of full license text
Are you open to replace this https://github.com/lstrojny/functional-php/blob/master/src/Functional/Contains.php#L2-L22 with proper file comment?

```php
/**
 * @package   Functional-php
 * @author    Lars Strojny <lstrojny@php.net>
 * @copyright 2011-2017 Lars Strojny
 * @license   https://opensource.org/licenses/MIT MIT
 * @link      https://github.com/lstrojny/functional-php
 */
```

https://docs.phpdoc.org/references/phpdoc/basic-syntax.html

### PR DESCRIPTION
**Pull request by szepeviktor**
Closes #199 

@lstrojny  
kép

### CODE REVIEW

**Comment by phanan** [comment]
While we're at it, maybe remove the years (for instance 2011-2017) for a more generic copyright duration?

**Comment by szepeviktor** [comment]
@phanan `sed` is your friend after this one gets merged :)

**Comment by phanan** [comment]
Sure, but “while we’re at it.”

Viktor Szépe <notifications@github.com> schrieb am Fr. 29. Nov. 2019 um
18:48:

**Comment by szepeviktor** [comment]
I've agreed with Lars on the inserted docblock.
I do not know what he thinks about this date removal.

**Comment by phanan** [comment]
Sorry, my original comment was meant for @lstrojny actually.

**Comment by lstrojny** [comment]
Fine with changing the date as well

**Pull request merged**
