### PR TITLE
Refactored first and last to throw exceptions if element is missing and added find.

### LINKED ISSUE #81: First and last should throw an error if the collection is empty.
I my opinion ```fist``` and ```last``` should throw sth like a ```NoSuchElementException``` if the collection is empty instead of returning ```null```. This would avoid the ambiguity with ```null``` as a value.
Further, I would prefer removing the callable argument and introduce a ```find``` function for that purpose.

P.S.: Great library. Thanks!

### PR DESCRIPTION
**Pull request by hoesler**
Closes #81

### CODE REVIEW

**Comment by lstrojny** [comment]
I don’t think we can just refactor the behavior of the existing methods like this. What about introducing a new set of functions like first_or_throw and last_or_throw?

**Comment by hoesler** [comment]
I see the problem that changing the current behavior would corrupt existing
code. Maybe I was a bit rash with this.
But honestly, using these functions when you can't be sure if null is the
first/last value or indicates an absent seems pointless to me. Throwing an
exception is much safer. Scala does exactly this.
But there is another less invasive option: Adding an argument for the
default return value. What about this?

Lars Strojny <notifications@github.com> schrieb am Di., 24. Nov. 2015 um
14:21 Uhr:

**Comment by lstrojny** [comment]
first() and last() returning null is OK when you have something like this:

```
/** @return Message|null */
public function getLatestMessage()
{
    return F\last($this->contacts);
}
```

Adding a parameter to change error handling behavior is a big a no, let’s make it explicit with new function names.

**Comment by hoesler** [comment]
Yes, it is definitely OK if you can be sure that null means absent and not
'null'. Regarding the alternative solution: the parameter I was imagining
was for the default return value (like in guavas getFirst,
http://docs.guava-libraries.googlecode.com/git/javadoc/index.html) not for
the exception logic. That would indeed be a big no go.

Lars Strojny <notifications@github.com> schrieb am Di., 24. Nov. 2015 um
14:56 Uhr:

**Comment by lstrojny** [comment]
To make sure I understand you correctly, you would do something like this:

```
function first($collection, callable $predicate = null, $defaultValue = null) {
    …
}
```
… and then introduce a flag for $defaultValue that enables the exception behavior?

**Comment by hoesler** [comment]
No. I my last response I was hoping to make that clear. The default value
is the value returned if the element is missing. No conditional exception
flag. But than again, if the default value argument must be given after the
unused predicate, I dislike this approach. MAYBE in the end the cleanest
way is indeed a new function like ```require_first```.

Lars Strojny <notifications@github.com> schrieb am Di., 24.11.2015, 23:32:

**Comment by lstrojny** [comment]
Yep, a new function is definitely the way to go.

**Pull request closed without merging**
