### PR TITLE
Add `ary` function which ignores arguments over the supplied number

### PR DESCRIPTION
**Pull request by someonewithpc**
Added function which defines a function of an arbitry number of arguments and
calls the provided callable with only the given number of arguments

Didn't add tests as it wasn't obvious how they worked and wanted feedback before investing the time

### CODE REVIEW

**Comment by lstrojny** [comment]
In lodash this function is called `ary`(https://lodash.com/docs/4.17.15#ary). What do you think?

**Comment by someonewithpc** [comment]
Maybe `arity`, then?

**Comment by lstrojny** [comment]
I would just follow lodash‘s naming precedence

**Comment by someonewithpc** [comment]
@lstrojny Renamed the function and added tests (the build fail seems to be unrelated and fixed by my other PR)

**Comment by someonewithpc** [comment]
@lstrojny Changed the function name and added tests (the failure seems to be unrelated, and fixed by my other PR)

**Comment by lstrojny** [comment]
Care to document the function in the docs as well?

**Comment by someonewithpc** [comment]
@lstrojny added documentation to the tests commit.

**Comment by lstrojny** [comment]
Great, thank you!

**Comment by someonewithpc** [comment]
How does it check those? I ran php-cs-fixer (from vendor/bin) and it didn't fiz it

**Comment by lstrojny** [comment]
> How does it check those? I ran php-cs-fixer (from vendor/bin) and it didn't fiz it

That PHP code sniffer. Run `phpcs` to see the errors.

**Comment by someonewithpc** [comment]
Ok, should be ready to merge, now

**Comment by lstrojny** [comment]
Great, thank you!

**Pull request merged**
